# SPDX-FileCopyrightText: Copyright (c) 2021-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
ec2:
  type: t2.2xlarge
assets:
  docker-password: yegor256/home#assets/docker-password
merge:
  script: |-
    sudo docker build "$(pwd)"
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i -e "s/0.0.0/${tag}/" entry.sh
    sed -i -e "s/0.0.0/${tag}/" Dockerfile
    sed -i -e "s/:latest/:${tag}/" action.yml
    git add entry.sh
    git add Dockerfile
    git add action.yml
    git commit -m "version set to ${tag}"
    sudo make "--directory=$(pwd)"
    repo=yegor256/latexmk-action
    sudo docker build "$(pwd)" --tag "${repo}:${tag}"
    sudo docker build "$(pwd)" --tag "${repo}:latest"
    cat ../docker-password | sudo docker login --password-stdin -u yegor256
    sudo docker push "${repo}:${tag}"
    sudo docker push "${repo}:latest"
